// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWUeqepPOlePd4dVpQYVokDDdvCDgM7g4',
    appId: '1:243591296486:web:da3ff609bdea65c31e1227',
    messagingSenderId: '243591296486',
    projectId: 'medwear-ce6e1',
    authDomain: 'medwear-ce6e1.firebaseapp.com',
    storageBucket: 'medwear-ce6e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWUeqepPOlePd4dVpQYVokDDdvCDgM7g4',
    appId: '1:243591296486:android:da3ff609bdea65c31e1227',
    messagingSenderId: '243591296486',
    projectId: 'medwear-ce6e1',
    storageBucket: 'medwear-ce6e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWUeqepPOlePd4dVpQYVokDDdvCDgM7g4',
    appId: '1:243591296486:ios:da3ff609bdea65c31e1227',
    messagingSenderId: '243591296486',
    projectId: 'medwear-ce6e1',
    storageBucket: 'medwear-ce6e1.firebasestorage.app',
    iosBundleId: 'com.medwear.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWUeqepPOlePd4dVpQYVokDDdvCDgM7g4',
    appId: '1:243591296486:macos:da3ff609bdea65c31e1227',
    messagingSenderId: '243591296486',
    projectId: 'medwear-ce6e1',
    storageBucket: 'medwear-ce6e1.firebasestorage.app',
    iosBundleId: 'com.medwear.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWUeqepPOlePd4dVpQYVokDDdvCDgM7g4',
    appId: '1:243591296486:windows:da3ff609bdea65c31e1227',
    messagingSenderId: '243591296486',
    projectId: 'medwear-ce6e1',
    storageBucket: 'medwear-ce6e1.firebasestorage.app',
  );
}
